const mongoose=require("mongoose");
const Question=require("../models/ques.js");

main()
.then(()=>{
    console.log("connected to database");
})
.catch(err => console.log(err));

async function main(){
    await mongoose.connect('mongodb://127.0.0.1:27017/ExamMaster');
}

Question.deleteMany({});

const questions = [
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 1,
        subject: "Mathematics",
        quesType: "MCQ",
        ques: "What is 2 + 2?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "3",
        opt1Img: "",
        opt2: "4",
        opt2Img: "",
        opt3: "5",
        opt3Img: "",
        opt4: "6",
        opt4Img: "",
        ans: "4",
    },
    {
        hostid:'67e59313e4d6f4e55f1dd378',
        paper: 1,
        subject: "Science",
        quesType: "MCQ",
        ques: "What is H2O?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Oxygen",
        opt1Img: "",
        opt2: "Water",
        opt2Img: "",
        opt3: "Hydrogen",
        opt3Img: "",
        opt4: "Carbon Dioxide",
        opt4Img: "",
        ans: "Water",
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 1,
        subject: "History",
        quesType: "MCQ",
        ques: "Who was the first President of the USA?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Abraham Lincoln",
        opt1Img: "",
        opt2: "George Washington",
        opt2Img: "",
        opt3: "Thomas Jefferson",
        opt3Img: "",
        opt4: "Theodore Roosevelt",
        opt4Img: "",
        ans: "George Washington",
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 1,
        subject: "Geography",
        quesType: "MCQ",
        ques: "Which is the largest ocean on Earth?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Atlantic Ocean",
        opt1Img: "",
        opt2: "Indian Ocean",
        opt2Img: "",
        opt3: "Arctic Ocean",
        opt3Img: "",
        opt4: "Pacific Ocean",
        opt4Img: "",
        ans: "Pacific Ocean",
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 1,
        subject: "Mathematics",
        quesType: "MCQ",
        ques: "What is the square root of 64?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "6",
        opt1Img: "",
        opt2: "7",
        opt2Img: "",
        opt3: "8",
        opt3Img: "",
        opt4: "9",
        opt4Img: "",
        ans: "8",
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 2,
        subject: "English",
        quesType: "MCQ",
        ques: "Which word is a synonym of 'Happy'?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Sad",
        opt1Img: "",
        opt2: "Angry",
        opt2Img: "",
        opt3: "Joyful",
        opt3Img: "",
        opt4: "Bored",
        opt4Img: "",
        ans: "Joyful"
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 2,
        subject: "Science",
        quesType: "MCQ",
        ques: "What planet is known as the Red Planet?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Earth",
        opt1Img: "",
        opt2: "Mars",
        opt2Img: "",
        opt3: "Venus",
        opt3Img: "",
        opt4: "Jupiter",
        opt4Img: "",
        ans: "Mars"
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 2,
        subject: "History",
        quesType: "MCQ",
        ques: "Which war ended in 1945?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "World War I",
        opt1Img: "",
        opt2: "World War II",
        opt2Img: "",
        opt3: "Cold War",
        opt3Img: "",
        opt4: "Vietnam War",
        opt4Img: "",
        ans: "World War II"
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 2,
        subject: "Geography",
        quesType: "MCQ",
        ques: "Which continent is known as the 'Dark Continent'?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Asia",
        opt1Img: "",
        opt2: "Africa",
        opt2Img: "",
        opt3: "Europe",
        opt3Img: "",
        opt4: "Australia",
        opt4Img: "",
        ans: "Africa"
    },
    {
        hostid: '67e59313e4d6f4e55f1dd378',
        paper: 2,
        subject: "English",
        quesType: "MCQ",
        ques: "Which of these is a noun?",
        isImg: false,
        quesImg: "",
        isOptImg: false,
        opt1: "Run",
        opt1Img: "",
        opt2: "Jump",
        opt2Img: "",
        opt3: "Table",
        opt3Img: "",
        opt4: "Quickly",
        opt4Img: "",
        ans: "Table"
    }
];

Question.insertMany(questions);
