const mongoose = require("mongoose");
const Question = require("../models/ques.js");

main()
  .then(() => {
    console.log("connected to database");
  })
  .catch((err) => console.log(err));

async function main() {
  await mongoose.connect("mongodb://127.0.0.1:27017/ExamMaster");
}

Question.deleteMany({});

const questions = [
  // q1 m
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "math",
    quesType: "SCQ",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/m-q1.png",
    isOptImg: true,
    opt1: "",
    opt1Img: "http://localhost:8000/q1-o1.png",
    opt2: "",
    opt2Img: "http://localhost:8000/q1-o2.png",
    opt3: "",
    opt3Img: "http://localhost:8000/q1-o3.png",
    opt4: "",
    opt4Img: "http://localhost:8000/q1-o4.png",
    ans: "B",
  },
  //   q2 - m
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "math",
    quesType: "SCQ",
    ques: "A student appears for a quiz consisting of only true-false type questions and answers all the questions. The student knows the answers of some questions and guesses the answers for the remaining questions.  Whenever the student knows the answer of a question, he gives the correct answer. Assume that the probability of the student giving the correct answer for a question, given that he has guessed it, is 1/2 Also assume that the probability of the answer for a question being guessed, given that the student's answer is correct, is 1/6 Then the probability that the student knows the answer of a randomly chosen question is ",
    isImg: false,
    quesImg: "",
    isOptImg: false,
    opt1: "1/12",
    opt1Img: "",
    opt2: "1/7",
    opt2Img: "",
    opt3: "5/7",
    opt3Img: "",
    opt4: "5/12",
    opt4Img: "",
    ans: "C",
  },
  {
    // q 3 - m
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "math",
    quesType: "MCQ",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/m-q3.png",
    isOptImg: true,
    opt1: "",
    opt1Img: "http://localhost:8000/q3-o1.png",
    opt2: "",
    opt2Img: "http://localhost:8000/q3-o2.png",
    opt3: "",
    opt3Img: "http://localhost:8000/q3-o3.png",
    opt4: "",
    opt4Img: "http://localhost:8000/q3-o4.png",
    ans: "ACD",
  },
  //   m-q4
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "math",
    quesType: "MCQ",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/m-q4.png",
    isOptImg: true,
    opt1: "",
    opt1Img: "http://localhost:8000/q4-o1.png",
    opt2: "",
    opt2Img: "http://localhost:8000/q4-o2.png",
    opt3: "",
    opt3Img: "http://localhost:8000/q4-o3.png",
    opt4: "",
    opt4Img: "http://localhost:8000/q4-o4.png",
    ans: "BCD",
  },
  //   m-q5
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "Mathematics",
    quesType: "Num",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/m-q5.png",
    isOptImg: false,
    opt1: "",
    opt1Img: "",
    opt2: "",
    opt2Img: "",
    opt3: "",
    opt3Img: "",
    opt4: "",
    opt4Img: "",
    ans: "8",
  },
  //   m-q6
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "math",
    quesType: "Num",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/m-q6.png",
    isOptImg: false,
    opt1: "",
    opt1Img: "",
    opt2: "",
    opt2Img: "",
    opt3: "",
    opt3Img: "",
    opt4: "",
    opt4Img: "",
    ans: "20",
  },
  //   p-q1
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "phy",
    quesType: "SCQ",
    ques: "A block of mass 5 kg moves along the x-direction subject to the force F = (-20x + 10) N, with the value of x in metre. At time t = 0 s, it is at rest at position x = 1 m. The position and momentum of the block at t = (𝜋/4) s are",
    isImg: false,
    quesImg: "",
    isOptImg: false,
    opt1: "-0.5 m, 5 kg m/s",
    opt1Img: "",
    opt2: "0.5 m, 0 kg m/s",
    opt2Img: "",
    opt3: "0.5 m, -5 kg m/s",
    opt3Img: "",
    opt4: "-1 m, 5 kg m/s",
    opt4Img: "",
    ans: "C",
  },
  // p-q2
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "phy",
    quesType: "SCQ",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/m-q6.png",
    isOptImg: false,
    opt1: "(2n,-n,-n,-n)",
    opt1Img: "",
    opt2: "(n,-n,-2n,-n)",
    opt2Img: "",
    opt3: "(n,-n,-n,-2n)",
    opt3Img: "",
    opt4: "(2n,-n,-2n,-2n)",
    opt4Img: "",
    ans: "A",
  },
  // p-q3
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "phy",
    quesType: "MCQ",
    ques: "A particle of mass 𝑚 is moving in a circular orbit under the influence of the central force F(r)=-kr, corresponding to the potential energy V(r)=kr^2/2, where k is a positive force constant and r is the radial distance from the origin. According to the Bohr's quantization rule, the angular momentum of the particle is given by L=𝑛ℏ, where ℏ'=h/(2𝜋), h is the Planck's constant, and n a positive integer. If v and E are the speed and total energy of the particle, respectively, then which of the following expression(s) is(are) correct?",
    isImg: false,
    quesImg: "",
    isOptImg: false,
    opt1: "",
    opt1Img: "http://localhost:8000/p-q3-o1.png",
    opt2: "",
    opt2Img: "http://localhost:8000/p-q3-o2.png",
    opt3: "",
    opt3Img: "http://localhost:8000/p-q3-o3.png",
    opt4: "",
    opt4Img: "http://localhost:8000/p-q3-o4.png",
    ans: "ABC",
  },
  // p-q4
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "phy",
    quesType: "MCQ",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/p-q4.png",
    isOptImg: false,
    opt1: "For n = 1.42, h = 50 cm.",
    opt1Img: "",
    opt2: "For n = 1.35, h = 36 cm.",
    opt2Img: "",
    opt3: "For n = 1.45, h = 65 cm.",
    opt3Img: "",
    opt4: "For n = 1.48, h = 85 cm.",
    opt4Img: "",
    ans: "AB",
  },
  // p-q5
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "phy",
    quesType: "Num",
    ques: " The specific heat capacity of a substance is temperature dependent and is given by the formula C = kT, where k is a constant of suitable dimensions in SI units, and T is the absolute temperature. If the heat required to raise the temperature of 1 kg of the substance from -73 °C to 27 °C is nk, the value of n is _____.",
    isImg: false,
    quesImg: "",
    isOptImg: false,
    opt1: "",
    opt1Img: "",
    opt2: "",
    opt2Img: "",
    opt3: "",
    opt3Img: "",
    opt4: "",
    opt4Img: "",
    ans: "25000",
  },
  // p-q6
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "phy",
    quesType: "Num",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/p-q6.png",
    isOptImg: false,
    opt1: "",
    opt1Img: "",
    opt2: "",
    opt2Img: "",
    opt3: "",
    opt3Img: "",
    opt4: "",
    opt4Img: "",
    ans: "12",
  },
  // c-q1
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "chem",
    quesType: "SCQ",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/c-q1.png",
    isOptImg: true,
    opt1: "",
    opt1Img: "http://localhost:8000/c-q1-o1.png",
    opt2: "",
    opt2Img: "http://localhost:8000/c-q1-o2.png",
    opt3: "",
    opt3Img: "http://localhost:8000/c-q1-o3.png",
    opt4: "",
    opt4Img: "http://localhost:8000/c-q1-o4.png",
    ans: "B",
  },
  // c-q2
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "chem",
    quesType: "SCQ",
    ques: "  A closed vessel contains 10 g of an ideal gas X at 300 K, which exerts 2 atm pressure. At the same temperature, 80 g of another ideal gas Y is added to it and the pressure becomes 6 atm. The ratio of root mean square velocities of X and Y at 300 K is",
    isImg: false,
    quesImg: "",
    isOptImg: false,
    opt1: "2√2 : √3",
    opt1Img: "",
    opt2: "2√2 : 1",
    opt2Img: "",
    opt3: "1 : 2",
    opt3Img: "",
    opt4: "2 : 1",
    opt4Img: "",
    ans: "D",
  },
  // c-q3
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "chem",
    quesType: "MCQ",
    ques: "Among the following, the correct statement(s) for electrons in an atom is(are) ",
    isImg: false,
    quesImg: "",
    isOptImg: false,
    opt1: "Uncertainty principle rules out the existence of definite paths for electrons.",
    opt1Img: "",
    opt2: "The energy of an electron in 2s orbital of an atom is lower than the energy of an electron that is infinitely far away from the nucleus.",
    opt2Img: "",
    opt3: "According to Bohr's model, the most negative energy value for an electron is given by n = 1, which corresponds to the most stable orbit.",
    opt3Img: "",
    opt4: "According to Bohr's model, the magnitude of velocity of electrons increases with increase in values of n.",
    opt4Img: "",
    ans: "ABC",
  },
  // c-q4
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "chem",
    quesType: "MCQ",
    ques: "Reaction of iso-propylbenzene with O2 followed by the treatment with H3O+ forms phenol and a by-product P. Reaction of P with 3 equivalents of Cl2 gives compound Q. Treatment of Q with Ca(OH)2 produces compound R and calcium salt S. The correct statement(s) regarding P, Q, R and S is(are) ",
    isImg: false,
    quesImg: "",
    isOptImg: true,
    opt1: "",
    opt1Img: "http://localhost:8000/c-q1-o3.png",
    opt2: "Reaction of R with O2 in the presence of light gives phosgene gas",
    opt2Img: "",
    opt3: "Q reacts with aqueous NaOH to produce Cl3CCH2OH and Cl3CCOONa",
    opt3Img: "",
    opt4: "S on heating gives P",
    opt4Img: "",
    ans: "ABD",
  },
  // c-q5
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "chem",
    quesType: "Num",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/c-q5.png",
    isOptImg: false,
    opt1: "",
    opt1Img: "",
    opt2: "",
    opt2Img: "",
    opt3: "",
    opt3Img: "",
    opt4: "",
    opt4Img: "",
    ans: "3",
  },
  // c-q6
  {
    hostid: "67e59313e4d6f4e55f1dd378",
    paper: 1,
    subject: "chem",
    quesType: "Num",
    ques: "",
    isImg: true,
    quesImg: "http://localhost:8000/c-q6.png",
    isOptImg: false,
    opt1: "",
    opt1Img: "",
    opt2: "",
    opt2Img: "",
    opt3: "",
    opt3Img: "",
    opt4: "",
    opt4Img: "",
    ans: "909",
  },
];

Question.insertMany(questions);
